version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: task_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: task_manager_web
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - .:/app
    links:
      - db

volumes:
  db_data:
  
networks:
  app_network:
    driver: bridge
